markdown: kramdown
permalink: /post/:title/
author: xuwei
description: If you have any language confusion,please talk me lindexi_gd@163.com.
url: /xuwei
highlighter: rouge
paginate: 30
gems: [jekyll-paginate]
excerpt_separator: "<!--more-->"
author:
    name: xuwei