markdown: kramdown
permalink: /post/:title/
author: lindexi
description: If you have any language confusion,please talk me lindexi_gd@163.com.
url: /lindexi
highlighter: rouge
paginate: 30
gems: [jekyll-paginate]
excerpt_separator: "<!--more-->"
author:
    name: lindexi